[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/infos.html"
  status = 302

[[redirects]]
  from = "/index.html"
  to = "/infos.html"
  status = 302

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200
